services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - configdir:/config
    restart: unless-stopped
    ports:
      - "8080:8080"
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "tsdproxy"
      tsdproxy.ephemeral: "false"

volumes:
  datadir:
  configdir: