services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "wud"
      tsdproxy.ephemeral: "false"